#!/bin/bash
#PBS -N PageRank_Benchmark_OpenMP
#PBS -j oe
#PBS -o omp2.txt
#PBS -e omp2.txt
#PBS -q short_cpuQ
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=64:mem=16gb

cd $PBS_O_WORKDIR
set -euo pipefail

STATS_FILE="results/omp2_stats.txt"
mkdir -p results

DATASETS=("stanford" "google")
THREADS_LIST=(1 2 4 8 16 32 64)
#PLACES=("threads" "cores")
#BIND=("spread" "close")
PLACES=("threads")
BIND=("spread")

module load perf || echo "Perf not found, continuing..."

echo "Running OMP2 Tests..."
for bind in "${BIND[@]}"; do
    for place in "${PLACES[@]}"; do
        for threads in "${THREADS_LIST[@]}"; do
            
            export OMP_NUM_THREADS=$threads
            export OMP_PROC_BIND=$bind
            export OMP_PLACES=$place
            
            for dataset in "${DATASETS[@]}"; do
                echo "OMP2 bind=${bind} place=${place} threads=${threads} dataset=${dataset}" >> "$STATS_FILE"
                perf stat -e cache-references,cache-misses,cycles,instructions \
                    bin/omp2 "datasets/${dataset}.csr" 10 2>> "$STATS_FILE"
            done
        done
    done
done

echo "OMP2 Benchmark Finished."
echo ""