#!/bin/bash
#PBS -N pagerank_test
#PBS -o output.txt
#PBS -e output.txt
#PBS -q short_cpuQ
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=32:mem=16gb

cd $PBS_O_WORKDIR

set -euo pipefail

STATS_FILE="stats.txt"
ITERATIONS=10
SCALE=5

datasets=("stanford" "google")

module load perf

# Sequential
echo "Running tests for sequential PageRank..."
for dataset in "${datasets[@]}"; do
    for ((i=0; i<$ITERATIONS; i++)); do
        echo "SEQ" >> "$STATS_FILE"
        perf stat -e cache-references,cache-misses,cycles,instructions \
            bin/seq datasets/${dataset}.csr 2>> "$STATS_FILE"
    done
done

# Shared memory
echo "Running tests for OpenMP PageRank..."
export OMP_NUM_THREADS=1
export OMP_PROC_BIND=close
export OMP_PLACES=cores

for ((j=0; j<$SCALE; j++)); do
    export OMP_NUM_THREADS=$((OMP_NUM_THREADS*2))
    echo "  N_THREADS=${OMP_NUM_THREADS}"

    for dataset in "${datasets[@]}"; do
        for ((i=0; i<$ITERATIONS; i++)); do
            echo "OMP ${OMP_NUM_THREADS}" >> "$STATS_FILE"
            perf stat -e cache-references,cache-misses,cycles,instructions \
                bin/omp datasets/${dataset}.csr 2>> "$STATS_FILE"
        done
    done
done

# TODO Distributed memory

module unload perf

echo "Done."
