#!/bin/bash
#PBS -N PageRank_Benchmark_Custom
#PBS -j oe
#PBS -o custom.txt
#PBS -e custom.txt
#PBS -q short_cpuQ
#PBS -l walltime=1:00:00
#PBS -l select=1:ncpus=64:mem=16gb

cd $PBS_O_WORKDIR
set -euo pipefail

STATS_FILE="results/custom_stats.txt"
mkdir -p results

DATASETS=("stanford" "google")
THREADS_LIST=(1 2 4 8 16 32 64)
PLACES=("threads" "cores")
BIND=("spread" "close")

module load perf || echo "Perf not found, continuing..."

echo "Running Sequential Baseline..."
for dataset in "${DATASETS[@]}"; do
    echo "SEQ threads=1 dataset=${dataset}" >> "$STATS_FILE"
    perf stat -e cache-references,cache-misses,cycles,instructions \
        bin/seq "datasets/${dataset}.csr" >> "$STATS_FILE" 2>&1
done
echo "Sequential tests finished"
echo ""

echo "Running OpenMP Tests..."
for bind in "${BIND[@]}"; do
    for place in "${PLACES[@]}"; do
        for threads in "${THREADS_LIST[@]}"; do
            
            export OMP_NUM_THREADS=$threads
            export OMP_PROC_BIND=$bind
            export OMP_PLACES=$place
            
            for dataset in "${DATASETS[@]}"; do
                echo "OMP bind=${bind} place=${place} threads=${threads} dataset=${dataset}" >> "$STATS_FILE"
                perf stat -e cache-references,cache-misses,cycles,instructions \
                    bin/omp "datasets/${dataset}.csr" 10 >> "$STATS_FILE" 2>&1
            done
        done
    done
done

echo "Custom Benchmark Finished."
echo ""