#!/bin/bash
#PBS -N PageRank_Benchmark_MPI
#PBS -j oe
#PBS -o mpi.txt
#PBS -e mpi.txt
#PBS -q short_cpuQ
#PBS -l walltime=1:00:00
#PBS -l select=4:ncpus=64:mem=16gb

cd $PBS_O_WORKDIR
set -euo pipefail

STATS_FILE="results/mpi_stats.txt"
mkdir -p results

DATASETS=(stanford google 100k 200k 400k 800k 1600k 3200k 6400k)
PROCESS_LIST=(1 2 4 8 16 32 64 128 256)

module load perf || echo "Perf not found, continuing..."
module load mpich-3.2.1--gcc-9.1.0 || echo "MPI not found, continuing..."
module load gcc91 || echo "GCC not found, continuing..."

echo "Running MPI Tests..."
for processes in "${PROCESS_LIST[@]}"; do
    for dataset in "${DATASETS[@]}"; do
        #mpirun -np $processes bash -c "perf stat -e cache-references,cache-misses,cycles,instructions \
        #    bin/mpi datasets/${dataset}.csr 10 >> \${PMI_RANK}_${STATS_FILE} 2>&1"
        mpirun -np $processes bash -c "bin/mpi datasets/${dataset}.csr 10 >> ${STATS_FILE} 2>&1"
    done
done

module unload perf
module unload mpich-3.2.1--gcc-9.1.0
module unload gcc91

echo "MPI Benchmark Finished."
echo ""